-- MySQL Script generated by MySQL Workbench
-- Sel 16 Jun 2020 04:17:59  WITA
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sidesa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sidesa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sidesa` DEFAULT CHARACTER SET latin1 ;
USE `sidesa` ;

-- -----------------------------------------------------
-- Table `sidesa`.`migration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidesa`.`migration` (
  `version` VARCHAR(180) NOT NULL,
  `apply_time` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`version`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sidesa`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidesa`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `auth_key` VARCHAR(32) CHARACTER SET 'utf8' NOT NULL,
  `password_hash` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `password_reset_token` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `status` SMALLINT(6) NOT NULL DEFAULT '10',
  `created_at` INT(11) NOT NULL,
  `updated_at` INT(11) NOT NULL,
  `verification_token` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC),
  UNIQUE INDEX `email` (`email` ASC),
  UNIQUE INDEX `password_reset_token` (`password_reset_token` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `sidesa`.`provinsi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidesa`.`provinsi` (
  `provinsi_id` INT NOT NULL AUTO_INCREMENT,
  `provinsi_kode` VARCHAR(45) NOT NULL,
  `provinsi_nama` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`provinsi_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sidesa`.`kabupaten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidesa`.`kabupaten` (
  `kabupaten_id` INT NOT NULL AUTO_INCREMENT,
  `kabupaten_kode` VARCHAR(45) NOT NULL,
  `kabupaten_nama` VARCHAR(45) NOT NULL,
  `provinsi_provinsi_id` INT NOT NULL,
  PRIMARY KEY (`kabupaten_id`),
  INDEX `fk_kabupaten_provinsi_idx` (`provinsi_provinsi_id` ASC),
  CONSTRAINT `fk_kabupaten_provinsi`
    FOREIGN KEY (`provinsi_provinsi_id`)
    REFERENCES `sidesa`.`provinsi` (`provinsi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sidesa`.`kecamatan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidesa`.`kecamatan` (
  `kecamatan_id` INT NOT NULL AUTO_INCREMENT,
  `kecamatan_kode` VARCHAR(45) NOT NULL,
  `kecamatan_nama` VARCHAR(45) NOT NULL,
  `kabupaten_kabupaten_id` INT NOT NULL,
  PRIMARY KEY (`kecamatan_id`),
  INDEX `fk_kecamatan_kabupaten1_idx` (`kabupaten_kabupaten_id` ASC),
  CONSTRAINT `fk_kecamatan_kabupaten1`
    FOREIGN KEY (`kabupaten_kabupaten_id`)
    REFERENCES `sidesa`.`kabupaten` (`kabupaten_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sidesa`.`desa_kelurahan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidesa`.`desa_kelurahan` (
  `desa_kelurahan_id` INT NOT NULL AUTO_INCREMENT,
  `desa_kelurahan_kode` VARCHAR(45) NOT NULL,
  `desa_kelurahan_nama` VARCHAR(145) NOT NULL,
  `kecamatan_id` INT NOT NULL,
  PRIMARY KEY (`desa_kelurahan_id`),
  INDEX `fk_desa_kelurahan_kecamatan1_idx` (`kecamatan_id` ASC),
  CONSTRAINT `fk_desa_kelurahan_kecamatan1`
    FOREIGN KEY (`kecamatan_id`)
    REFERENCES `sidesa`.`kecamatan` (`kecamatan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sidesa`.`dusun_rw`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidesa`.`dusun_rw` (
  `dusun_rw_id` INT NOT NULL AUTO_INCREMENT,
  `dusun_rw_kode` VARCHAR(45) NOT NULL,
  `dusun_rw_nama` VARCHAR(145) NULL,
  `desa_kelurahan_id` INT NOT NULL,
  PRIMARY KEY (`dusun_rw_id`),
  INDEX `fk_dusun_rw_desa_kelurahan1_idx` (`desa_kelurahan_id` ASC),
  CONSTRAINT `fk_dusun_rw_desa_kelurahan1`
    FOREIGN KEY (`desa_kelurahan_id`)
    REFERENCES `sidesa`.`desa_kelurahan` (`desa_kelurahan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sidesa`.`keluarga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidesa`.`keluarga` (
  `keluarga_id` INT NOT NULL AUTO_INCREMENT,
  `keluarga_kode` VARCHAR(45) NOT NULL,
  `keluarga_kk` VARCHAR(45) NULL,
  `dusun_rw_id` INT NOT NULL,
  `alamat` VARCHAR(45) NULL,
  PRIMARY KEY (`keluarga_id`),
  INDEX `fk_keluarga_dusun_rw1_idx` (`dusun_rw_id` ASC),
  CONSTRAINT `fk_keluarga_dusun_rw1`
    FOREIGN KEY (`dusun_rw_id`)
    REFERENCES `sidesa`.`dusun_rw` (`dusun_rw_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sidesa`.`agama`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidesa`.`agama` (
  `agama_id` INT NOT NULL AUTO_INCREMENT,
  `nama_agama` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`agama_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sidesa`.`pendidikan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidesa`.`pendidikan` (
  `pendidikan_id` INT NOT NULL AUTO_INCREMENT,
  `nama_pendidikan` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pendidikan_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sidesa`.`pekerjaan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidesa`.`pekerjaan` (
  `pekerjaan_id` INT NOT NULL AUTO_INCREMENT,
  `nama_pekerjaan` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pekerjaan_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sidesa`.`status_perkawinan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidesa`.`status_perkawinan` (
  `status_perkawinan_id` INT NOT NULL AUTO_INCREMENT,
  `nama_status_perkawinan` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`status_perkawinan_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sidesa`.`golongan_darah`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidesa`.`golongan_darah` (
  `golongan_darah_id` INT NOT NULL AUTO_INCREMENT,
  `nama_golongan_darah` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`golongan_darah_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sidesa`.`status_hubungan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidesa`.`status_hubungan` (
  `status_hubungan_id` INT NOT NULL AUTO_INCREMENT,
  `status_hubungan_nama` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`status_hubungan_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sidesa`.`anggota_keluarga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidesa`.`anggota_keluarga` (
  `anggota_keluarga_id` INT NOT NULL AUTO_INCREMENT,
  `nik` VARCHAR(45) NOT NULL,
  `nama` VARCHAR(145) NOT NULL,
  `keluarga_id` INT NOT NULL,
  `gelar_depan` VARCHAR(45) NULL,
  `gelar_belakang` VARCHAR(45) NULL,
  `jenis_kelamin` ENUM('LAKI-LAKI', 'PEREMPUAN') NOT NULL,
  `tempat_lahir` VARCHAR(45) NULL,
  `tgl_lahir` DATE NULL,
  `agama_id` INT NOT NULL,
  `pendidikan_id` INT NULL,
  `pekerjaan_id` INT NULL,
  `golongan_darah_id` INT NULL,
  `status_perkawinan_id` INT NULL,
  `tgl_perkawinan` DATE NULL,
  `status_hubungan_status_hubungan_id` INT NOT NULL,
  `no_paspor` VARCHAR(45) NULL,
  `no_kitap` VARCHAR(45) NULL,
  `ayah` VARCHAR(145) NULL,
  `ibu` VARCHAR(45) NULL,
  PRIMARY KEY (`anggota_keluarga_id`),
  INDEX `fk_anggota_keluarga_agama1_idx` (`agama_id` ASC),
  INDEX `fk_anggota_keluarga_pendidikan1_idx` (`pendidikan_id` ASC),
  INDEX `fk_anggota_keluarga_pekerjaan1_idx` (`pekerjaan_id` ASC),
  INDEX `fk_anggota_keluarga_status_perkawinan1_idx` (`status_perkawinan_id` ASC),
  INDEX `fk_anggota_keluarga_golongan_darah1_idx` (`golongan_darah_id` ASC),
  INDEX `fk_anggota_keluarga_status_hubungan1_idx` (`status_hubungan_status_hubungan_id` ASC),
  INDEX `fk_anggota_keluarga_keluarga1_idx` (`keluarga_id` ASC),
  CONSTRAINT `fk_anggota_keluarga_agama1`
    FOREIGN KEY (`agama_id`)
    REFERENCES `sidesa`.`agama` (`agama_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anggota_keluarga_pendidikan1`
    FOREIGN KEY (`pendidikan_id`)
    REFERENCES `sidesa`.`pendidikan` (`pendidikan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anggota_keluarga_pekerjaan1`
    FOREIGN KEY (`pekerjaan_id`)
    REFERENCES `sidesa`.`pekerjaan` (`pekerjaan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anggota_keluarga_status_perkawinan1`
    FOREIGN KEY (`status_perkawinan_id`)
    REFERENCES `sidesa`.`status_perkawinan` (`status_perkawinan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anggota_keluarga_golongan_darah1`
    FOREIGN KEY (`golongan_darah_id`)
    REFERENCES `sidesa`.`golongan_darah` (`golongan_darah_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anggota_keluarga_status_hubungan1`
    FOREIGN KEY (`status_hubungan_status_hubungan_id`)
    REFERENCES `sidesa`.`status_hubungan` (`status_hubungan_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anggota_keluarga_keluarga1`
    FOREIGN KEY (`keluarga_id`)
    REFERENCES `sidesa`.`keluarga` (`keluarga_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5
COLLATE = big5_bin;


-- -----------------------------------------------------
-- Table `sidesa`.`jenis_perangkat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidesa`.`jenis_perangkat` (
  `jenis_perangkat_id` INT NOT NULL AUTO_INCREMENT,
  `nama_perangkat` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`jenis_perangkat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sidesa`.`perangkat_desa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidesa`.`perangkat_desa` (
  `perangkat_desa_id` INT NOT NULL AUTO_INCREMENT,
  `anggota_keluarga_id` INT NOT NULL,
  `jenis_perangkat_id` INT NOT NULL,
  `status` ENUM('Y', 'N') NULL,
  `tgl_lantik` DATE NULL,
  `tgl_berhenti` DATE NULL,
  `no_sk_lantik` VARCHAR(45) NULL,
  `no_sk_berhenti` VARCHAR(45) NULL,
  `file_sk_lantik` VARCHAR(145) NULL,
  `file_sk_berhenti` VARCHAR(45) NULL,
  INDEX `fk_perangkat_desa_anggota_keluarga1_idx` (`anggota_keluarga_id` ASC),
  INDEX `fk_perangkat_desa_jenis_perangkat1_idx` (`jenis_perangkat_id` ASC),
  PRIMARY KEY (`perangkat_desa_id`),
  CONSTRAINT `fk_perangkat_desa_anggota_keluarga1`
    FOREIGN KEY (`anggota_keluarga_id`)
    REFERENCES `sidesa`.`anggota_keluarga` (`anggota_keluarga_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_perangkat_desa_jenis_perangkat1`
    FOREIGN KEY (`jenis_perangkat_id`)
    REFERENCES `sidesa`.`jenis_perangkat` (`jenis_perangkat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sidesa`.`jenis_surat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidesa`.`jenis_surat` (
  `jenis_surat_id` INT NOT NULL AUTO_INCREMENT,
  `jenis_surat_nama` VARCHAR(145) NOT NULL,
  `pengantar` TEXT NULL,
  `penutup` TEXT NULL,
  `an_ttd` VARCHAR(45) NULL,
  PRIMARY KEY (`jenis_surat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sidesa`.`surat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidesa`.`surat` (
  `surat_id` INT NOT NULL AUTO_INCREMENT,
  `surat_nomor` VARCHAR(45) NOT NULL,
  `jenis_surat_id` INT NOT NULL,
  `tgl_surat` VARCHAR(45) NULL,
  `perangkat_desa_id` INT NOT NULL,
  `anggota_keluarga_id` INT NOT NULL,
  PRIMARY KEY (`surat_id`),
  INDEX `fk_surat_jenis_surat1_idx` (`jenis_surat_id` ASC),
  INDEX `fk_surat_perangkat_desa1_idx` (`perangkat_desa_id` ASC),
  INDEX `fk_surat_anggota_keluarga1_idx` (`anggota_keluarga_id` ASC),
  CONSTRAINT `fk_surat_jenis_surat1`
    FOREIGN KEY (`jenis_surat_id`)
    REFERENCES `sidesa`.`jenis_surat` (`jenis_surat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_surat_perangkat_desa1`
    FOREIGN KEY (`perangkat_desa_id`)
    REFERENCES `sidesa`.`perangkat_desa` (`perangkat_desa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_surat_anggota_keluarga1`
    FOREIGN KEY (`anggota_keluarga_id`)
    REFERENCES `sidesa`.`anggota_keluarga` (`anggota_keluarga_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sidesa`.`berita_kategori`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidesa`.`berita_kategori` (
  `berita_kategori_id` INT NOT NULL AUTO_INCREMENT,
  `berita_kategori_nama` VARCHAR(45) NULL,
  PRIMARY KEY (`berita_kategori_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sidesa`.`berita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidesa`.`berita` (
  `berita_id` INT NOT NULL AUTO_INCREMENT,
  `judul` VARCHAR(45) NULL,
  `isi` TEXT NULL,
  `foto` VARCHAR(45) NULL,
  `berita_kategori_id` INT NOT NULL,
  PRIMARY KEY (`berita_id`),
  INDEX `fk_berita_berita_kategori1_idx` (`berita_kategori_id` ASC),
  CONSTRAINT `fk_berita_berita_kategori1`
    FOREIGN KEY (`berita_kategori_id`)
    REFERENCES `sidesa`.`berita_kategori` (`berita_kategori_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
